### ISSUE TITLE
Does someone know how to install the "updatebyquery" plugin in local? for the server cannot connect to Internert

### ISSUE THREAD

**Issue by timesgarden** [yakaz/elasticsearch-action-updatebyquery#28]
Does someone know how to install the "updatebyquery" plugin in local? for the server cannot connect to Internert?
thanks in advance!

**Comment by ofavre** [comment]
You can upload the zip file to the server and then use elasticsearch's bin/plugin script to install it, using `--url` and a file:// URI, or simply do it manually by creating the plugins/updatebyquery/ (or whatever name you like) folder under your ES installation path.
This is applicable to any plugin.
See http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/modules-plugins.html#_plugins

**Comment by timesgarden** [comment]
thanks very much sir
