### ISSUE TITLE
Question: How to read a script from a file?

### ISSUE THREAD

**Issue by k4200** [yakaz/elasticsearch-action-updatebyquery#31]
Hi,

Thanks for this useful plugin. I'm testing it for our project, and it works as expected when using a dynamic script. Now, I'd like to have it load a script from a file under `scripts` directory, but I couldn't seem to get it to work.

> script: The script name or source.

I followed the doc and did like the following, but it didn't work:

```
curl -XPOST 'localhost:9200/foo/bar/_update_by_query' -d '
{
    "query": {"match_all" : { }},
    "script": "baz.groovy",
    "lang": "groovy",
    "params": {
        "param1": 3,
        "param2": 4
    }
}'
```

Thanks in advance.

**Comment by ofavre** [comment]
I'm afraid this is not currently possible.
It would require the parsing of the `script_id` or `script_file` fields in [`RestUpdateByQueryAction.handleRequest()`](https://github.com/yakaz/elasticsearch-action-updatebyquery/blob/master/src/main/java/org/elasticsearch/rest/action/updatebyquery/RestUpdateByQueryAction.java#L62), and modifying the [`UpdateRequest`](https://github.com/yakaz/elasticsearch-action-updatebyquery/blob/master/src/main/java/org/elasticsearch/action/updatebyquery/TransportShardUpdateByQueryAction.java#L331) to use an overloaded `script()` function and provide the corresponding `ScriptType`.

**Comment by k4200** [comment]
Thanks for your quick reply. I'll try to modify the plugin and send a PR (if success).
