### ISSUE TITLE
Not updating any documents

### ISSUE THREAD

**Issue by redserpent7** [yakaz/elasticsearch-action-updatebyquery#33]
Hi,

I am trying to update several documents at the same time using the update by query plugin.

The problem seems to be with the script as the query it self returns the correct result with no issues. The thing is ES seems to be able to execute the script as there are no exceptions in the logs. Yet nothing gets updated.

So here is the document I am indexing:

curl -XPUT 'localhost:9200/users/files/1' -d '{
         "path" : "path/to/file"
         "size": 200
}'

No here is my update by query request to change the path field from 'path/to/file' to 'another/path/to/file':

curl -XPOST  'localhost:9200/users/files/_update_by_query' -d ' 
{
  "query": {
    "bool": {
      "must": [
        {
          "term": {
            "path": "path/to/file"
          }
        }]
    }
  },
  "script": "def str = ctx_source.path;\ndef str2 = str.replaceAll(\"path/to/file\", \"another/path/to/file\");\nctx._source.path = str2;"
}'

And this is what I get:
{
  "ok":true,
  "took":516,
  "total":75,
  "updated":0,
  "indices":[
    {
      "new_index":{}
    }]
}

so the query matched 75 documents but did not update any.
Anyone knows how can I make it work.

**Here is the script in pretty form:

 def str = ctx_source.path;
 def str2 = str.replaceAll("path/to/file", "another/path/to/file");
 ctx._source.path = str2;

**Comment by ofavre** [comment]
Can you make sure that dynamic scripting is enabled in your ES 1.2.0+ configuration?
Simply add `script.disable_dynamic: false` to your elasticsearch configuration.

**Comment by redserpent7** [comment]
NVM, found the culprit.

Was missing a '.':

def str = ctx_source.path; -> def str = ctx._source.path;

Weird how there was nothing in the logs about this
