### ISSUE TITLE
Problem related usage

### ISSUE THREAD

**Issue by raunakb94** [yakaz/elasticsearch-action-updatebyquery#44]
I am using ES-1.7.0.
I wanted to update certain document based on a query

I installed plugin on all the nodes.
Now ,
1. Doing post request on this url -> `http://host:9200/abc-2015-07-25/_update_by_query`
with body as 
```
{
  "query": {
    "filtered": {
      "filter": {
        "bool": {
          "must": [
            {"exists": {
              "field": "a"
            }},
            {"exists" : {
              "field": "b"
            }}
          ]
        }
      }
    }
  },
  "script":"ctx._source.uid = ctx._source.a + ctx._source.b"
}
```

I am always getting a response as 
```
{
  "error": "RemoteTransportException[[es-node-4][inet[/host:9300]][indices:data/write/index]]; nested: InvalidTypeNameException[mapping type name [_update_by_query] can't start with '_']; ",
  "status": 400
}
```

**Comment by ofavre** [comment]
It looks like you've missed something.
Maybe you forgot to restart each node after installing the plugin?

**Comment by raunakb94** [comment]
Is it necessary to restart the node?? and also do I need to install the plugin on all the nodes?

**Comment by ofavre** [comment]
A plugin is not loaded until the restart of the node (maybe it's different for _site_ plugins, dunno), so you have to restart the node after installing any plugin.
You have to restart all nodes for this plugin (like most non _site_ plugins I guess), as it distributes operations on each node of your cluster.
However, there is no need for a full cluster restart, a [rolling restart](https://www.elastic.co/guide/en/elasticsearch/reference/current/setup-upgrade.html#rolling-upgrades) suffices.

Please close the ticket if this fixes your problem.
